# open your Github project repository and get into settings page.
# On the left side options,
# look for the security session and click on "Secrets" > "Actions".

# We need to create 3 secret keys. Each one for:
# FIREBASE_APP_ID
# FIREBASE_TOKEN
# GOOGLE_SERVICES_JSON

# Firebase token can be obtained by running a few commands on your machine
# npm install -g firebase-tools
# firebase login:ci

#name: Firebase APP workflow
#on:
#  push:
#    branches:
#      - main
#jobs:
#  firebase_app:
#    name: Run Firebase Workflow
#    ## virtual machine
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"

#     - name: Decode google-services.json
#       env:
#         GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
#       run: echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json

#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "stable"
#      - run: flutter clean
#      - run: flutter pub get
#      - run: flutter build apk --release
#      - uses: actions/upload-artifact@v1
#        with:
#         name: release-apk
#          path: build/app/outputs/apk/release/app-release.apk
#      - name: Upload to Firebase App Distribution
#        uses: wzieba/Firebase-Distribution-Github-Action@v1
#        with:
#          appId: ${{secrets.FIREBASE_APP_ID}}
#          token: ${{secrets.FIREBASE_TOKEN}}
#          groups: WorkDone Testers
#          file: build/app/outputs/apk/release/app-release.apk
          #file: build/app/outputs/flutter-apk/app.apk

